apiVersion: v1
kind: Service
metadata:
  name: cookedpad-auth
  namespace: cookedpad
  labels:
    app: cookedpad-auth
spec:
  type: ClusterIP
  selector:
    app: cookedpad-auth
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
