apiVersion: v1
kind: Service
metadata:
  name: cookedpad-comments
  namespace: cookedpad
  labels:
    app: cookedpad-comments
spec:
  type: ClusterIP
  selector:
    app: cookedpad-comments
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
