apiVersion: v1
kind: Service
metadata:
  name: cookedpad-frontend-service
  namespace: cookedpad
  labels:
    app: cookedpad-frontend
spec:
  type: LoadBalancer
  selector:
    app: cookedpad-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
