apiVersion: v1
kind: Service
metadata:
  name: cookedpad-recipes
  namespace: cookedpad
  labels:
    app: cookedpad-recipes
spec:
  type: ClusterIP
  selector:
    app: cookedpad-recipes
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
