apiVersion: v1
kind: Service
metadata:
  name: cookedpad-users
  namespace: cookedpad
  labels:
    app: cookedpad-users
spec:
  type: ClusterIP
  selector:
    app: cookedpad-users
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
